name: INSTRUMENT_NAME
api_ref: examples/instrument-apis/agi_34401a.yaml
connection:
  type: VISA
  address: TCPIP::192.168.0.1::INSTR::0
io_config:
  voltage:
    type: float
    role: input
    unit: V
    offset: 0
    scale: 1
  measured_voltage:
    type: float
    role: output
    unit: V
    offset: 0
    scale: 1